name: Update Dialtone 7

on:
  push:
    branches:
      - staging

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  update_version_7:
    runs-on: ubuntu-latest
    name: Cherry pick into version7
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Cherry pick
        uses: carloscastrojumo/github-cherry-pick-action@v1.0.1
        with:
          branch: version7
          labels: |
            cherry-pick
          reviewers: |
            braddialpad
            josedialpad
            juliodialpad
